<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}

use TVA_Manager;

$filters = [
    'meta_query' => [
        [
            'key'     => 'tva_is_demo',
            'compare' => 'NOT EXISTS',
        ],
    ],
    'orderby'    => 'id',
    'order'      => 'ASC',
];   

?>

<table id="tva-grades-table">
    <thead>
        <tr>
            <th>
                <?php echo __( 'Assessment title', 'thrive-apprentice' ); ?>
            </th>
            <th>
                <?php echo __( 'Weighted value', 'thrive-apprentice' ); ?>
            </th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>


    <?php foreach ( TVA_Manager::get_assessments( $filters) as $assessment ): ?>
        <?php
        // get assement course
        $course = $assessment->get_course_v2();
        $course_id = $course ? $course->get_id() : 0;
        ?>

        <# if ( this.model.get('course_id') == <?php echo $course_id; ?> ) { #>
            <tr class="tva-included" assessment-status="<?php echo $assessment->post_status; ?>" assessment-id="<?php echo $assessment->ID; ?>">
                <td class="assessment-title-container">
                    <?php 
                        echo $assessment->post_title;                    
                    ?>
                </td>
                <td class="assessment-weight-type-container">
                    <span class="val-checked left-border" data-value="automatic">Automatic</span>
                    <span class="right-border" data-value="manual">Manual</span>
                </td>
                <td class="assessment-weight-value-container">
                    <input type="text" value="">
                </td>
                <td colspan="2" class="assessment-included-excluded-container">
                    <div class="included-excluded-inside">
                        <?php esc_html_e('EXCLUDED', 'thrive-apprentice' ); ?>
                    </div>  
                </td>
                <td class="included-excluded" data-fn="tvaToggleAssessment">
                    <span class="icon-plus tva-tooltip-parent">
                        <?php tva_get_svg_icon( 'plus-circle' ); ?> 
                        <span class="tva-custom-tooltip include-exclude-tooltip">
                            <strong><?php echo __( 'Include', 'thrive-apprentice' ); ?></strong> <?php echo __( 'this assessment in overall grading', 'thrive-apprentice' ); ?>
                        </span>
                    </span>
                    <span class="icon-minus tva-tooltip-parent">
                        <?php tva_get_svg_icon( 'minus-circle' ); ?>
                        <span class="tva-custom-tooltip include-exclude-tooltip">
                            <strong><?php echo __( 'Exclude', 'thrive-apprentice' ); ?></strong> <?php echo __( 'this assessment from overall grading', 'thrive-apprentice' ); ?>
                        </span>
                    </span>
                </td>
            </tr>
        <# } #>
        
    <?php endforeach; ?>
    
    </tbody>
    <tfoot class="tva-hidden">
        <tr class="tva-included" assessment-id="">
            <td class="assessment-title-container"></td>
            <td class="assessment-weight-type-container">
                <span class="val-checked left-border" data-value="automatic">Automatic</span>
                <span class="right-border" data-value="manual">Manual</span>
            </td>
            <td class="assessment-weight-value-container">
                <input type="text" value="">
            </td>
            <td colspan="2" class="assessment-included-excluded-container">
                <div class="included-excluded-inside">
                    <?php esc_html_e('EXCLUDED', 'thrive-apprentice' ); ?>
                </div>  
            </td>
            <td class="included-excluded" data-fn="tvaToggleAssessment">
                <span class="icon-plus tva-tooltip-parent">
                    <?php tva_get_svg_icon( 'plus-circle' ); ?> 
                    <span class="tva-custom-tooltip include-exclude-tooltip">
                        <strong><?php echo __( 'Include', 'thrive-apprentice' ); ?></strong> <?php echo __( 'this assessment in overall grading', 'thrive-apprentice' ); ?>
                    </span>
                </span>
                <span class="icon-minus tva-tooltip-parent">
                    <?php tva_get_svg_icon( 'minus-circle' ); ?>
                    <span class="tva-custom-tooltip include-exclude-tooltip">
                        <strong><?php echo __( 'Exclude', 'thrive-apprentice' ); ?></strong> <?php echo __( 'this assessment from overall grading', 'thrive-apprentice' ); ?>
                    </span>
                </span>
            </td>
        </tr>
    </tfoot>
</table>
<input 
    type="hidden" 
    id="tva_assessments_weight_data" 
    data-course="<#= this.model.get('course_id') #>" 
    data-fn="assessmentDataChange" 
    value=""
    class="change"
    data-field="weight_data" />
<div id="tva-grade-weight-warning" class="tva-completion-tab-warning danger-warning">
    <?php tva_get_svg_icon( 'warning-red' ); ?>
    <p>
        <span><?php esc_html_e( 'Current total weighted value is', 'thrive-apprentice' ) ?></span> <span class="tva-strong-red"></span>
        <br />
        <span><?php esc_html_e( 'Overall grade will not work as desired unless the weighted value totals', 'thrive-apprentice' ) ?></span>
        <span class="tva-strong">100%</span>
    </p>
</div>
<div id="tva-grade-empty-weight-warning" class="tva-completion-tab-warning orange-warning">
    <?php tva_get_svg_icon( 'info-circle_light' ); ?>
    <p>
        <span><?php esc_html_e( 'At the moment you do not have any assessment included. You must have at least one assessment included to proceed the calculation', 'thrive-apprentice' ) ?></span>
    </p>
</div>
<div id="tva-grade-empty-weight-warning-second" class="tva-completion-tab-warning orange-warning">
    <?php tva_get_svg_icon( 'info-circle_light' ); ?>
    <p>
        <span><?php esc_html_e( 'At the moment you do not have any assessment published. Go add and publish your first assessment on the', 'thrive-apprentice' ) ?></span>
        <a href="#" class="click" data-fn="tvaGoToContentTab"><?php esc_html_e( 'Content tab', 'thrive-apprentice' ) ?></a>.
    </p>
</div>
