<div class="tvd-modal-content">
	<h3><?php echo __( 'Creating a Square Product', 'thrive-apprentice' ); ?></h3>
	<p><?php echo __( 'Don\'t worry, it\'s not rocket science. Follow the steps below' ); ?></p>
</div>
<div class="tvd-modal-step" data-step="0">
	<div class="tvd-modal-content mt-0 pt-0">
		<div class="tva-square-step-message mb-15">
			<div class="tva-square-number">1</div>
			<span><?php echo __( 'Open Square Product Dashboard & click add a product', 'thrive-apprentice' ); ?></span></div>
		<img alt="Square help" src="<?php echo TVA_Const::plugin_url( 'admin/img/square-helper.png' ); ?>">
	</div>
	<div class="tva-modal-footer-outer">
		<button type="button" class="tva-modal-btn tvd-modal-close">
			<?php echo esc_html__( 'Back', 'thrive-cb' ); ?>
		</button>
		<div class="tva-step-dots">
			<div class="tva-step-dot active"></div>
			<div class="tva-step-dot"></div>
			<div class="tva-step-dot"></div>
			<div class="tva-step-dot"></div>
			<div class="tva-step-dot"></div>
		</div>
		<button type="button" class="tva-modal-btn tva-modal-btn-blue tvd-modal-next-step">
			<?php echo esc_html__( 'Next', 'thrive-cb' ); ?>
		</button>
	</div>
</div>
<div class="tvd-modal-step" data-step="1">
	<div class="tvd-modal-content mt-0 pt-0">
		<div class="tva-square-step-message mb-15">
			<div class="tva-square-number">2</div>
			<span><?php echo __( 'Add your product details and save', 'thrive-apprentice' ); ?></span></div>
		<img alt="Square help" src="<?php echo TVA_Const::plugin_url( 'admin/img/square-helper-2.png' ); ?>">
	</div>
	<div class="tva-modal-footer-outer">
		<button type="button" class="tva-modal-btn tvd-modal-prev-step">
			<?php echo esc_html__( 'Back', 'thrive-cb' ); ?>
		</button>
		<div class="tva-step-dots">
			<div class="tva-step-dot"></div>
			<div class="tva-step-dot active"></div>
			<div class="tva-step-dot"></div>
			<div class="tva-step-dot"></div>
			<div class="tva-step-dot"></div>
		</div>
		<button type="button" class="tva-modal-btn tva-modal-btn-blue tvd-modal-next-step">
			<?php echo esc_html__( 'Next', 'thrive-cb' ); ?>
		</button>
	</div>
</div>
<div class="tvd-modal-step" data-step="2">
	<div class="tvd-modal-content mt-0 pt-0">
		<div class="tva-square-step-message mb-15">
			<div class="tva-square-number">3</div>
			<span><?php echo __( 'Return to Apprentice & refresh Square product list', 'thrive-apprentice' ); ?></span></div>
		<img alt="Square help" src="<?php echo TVA_Const::plugin_url( 'admin/img/square-helper-3.png' ); ?>">
	</div>
	<div class="tva-modal-footer-outer">
		<button type="button" class="tva-modal-btn tvd-modal-prev-step">
			<?php echo esc_html__( 'Back', 'thrive-cb' ); ?>
		</button>
		<div class="tva-step-dots">
			<div class="tva-step-dot"></div>
			<div class="tva-step-dot"></div>
			<div class="tva-step-dot active"></div>
			<div class="tva-step-dot"></div>
			<div class="tva-step-dot"></div>
		</div>
		<button type="button" class="tva-modal-btn tva-modal-btn-blue tvd-modal-next-step">
			<?php echo esc_html__( 'Next', 'thrive-cb' ); ?>
		</button>
	</div>
</div>
<div class="tvd-modal-step" data-step="3">
	<div class="tvd-modal-content mt-0 pt-0">
		<div class="tva-square-step-message mb-15">
			<div class="tva-square-number">4</div>
			<span><?php echo __( 'Select Square Product and you\'re done!', 'thrive-apprentice' ); ?></span></div>
		<img alt="Square help" src="<?php echo TVA_Const::plugin_url( 'admin/img/square-helper-4.png' ); ?>">
	</div>
	<div class="tva-modal-footer-outer">
		<button type="button" class="tva-modal-btn tvd-modal-prev-step">
			<?php echo esc_html__( 'Back', 'thrive-cb' ); ?>
		</button>
		<div class="tva-step-dots">
			<div class="tva-step-dot"></div>
			<div class="tva-step-dot"></div>
			<div class="tva-step-dot"></div>
			<div class="tva-step-dot active"></div>
			<div class="tva-step-dot"></div>
		</div>
		<button type="button" class="tva-modal-btn tva-modal-btn-blue tvd-modal-next-step">
			<?php echo esc_html__( 'Next', 'thrive-cb' ); ?>
		</button>
	</div>
</div>
<div class="tvd-modal-step" data-step="4">
	<div class="tvd-modal-content mt-0 pt-0">
		<div class="tva-square-step-message mb-15">
			<div class="tva-square-number">5</div>
			<span><?php echo __( 'Pro tip: You can copy your test products to your live Square environment', 'thrive-apprentice' ); ?></span></div>
		<img alt="Square help" src="<?php echo TVA_Const::plugin_url( 'admin/img/square-helper-2.png' ); ?>">
	</div>
	<div class="tva-modal-footer-outer">
		<button type="button" class="tva-modal-btn tvd-modal-prev-step">
			<?php echo esc_html__( 'Back', 'thrive-cb' ); ?>
		</button>
		<div class="tva-step-dots">
			<div class="tva-step-dot"></div>
			<div class="tva-step-dot"></div>
			<div class="tva-step-dot"></div>
			<div class="tva-step-dot"></div>
			<div class="tva-step-dot active"></div>
		</div>
		<button type="button" class="tva-modal-btn tva-modal-btn-blue tvd-modal-close">
			<?php echo esc_html__( 'Got it!', 'thrive-cb' ); ?>
		</button>
	</div>
</div>
