<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-apprentice
 */

namespace TVA\PayPal;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}

/**
 * Class Credentials
 *
 * Handles storage and retrieval of PayPal OAuth credentials in wp_options.
 * All options use autoload = false so they are never loaded on every page request.
 */
class Credentials {

	public const CREDENTIALS_ENDPOINT_OPTION      = 'tva_paypal_credentials_endpoint';
	public const CREDENTIALS_ENDPOINT_OPTION_LIVE = 'tva_paypal_credentials_endpoint_live';
	public const STATE_OPTION                      = 'tva_paypal_connection_state';
	public const STATE_OPTION_LIVE                 = 'tva_paypal_connection_state_live';
	/** @deprecated Unused in new Product API bearer-token flow. */
	public const ACCESS_TOKEN_OPTION               = 'tva_paypal_access_token';
	/** @deprecated Unused in new Product API bearer-token flow. */
	public const ACCESS_TOKEN_OPTION_LIVE          = 'tva_paypal_access_token_live';
	/** @deprecated Unused in new Product API bearer-token flow. */
	public const REFRESH_TOKEN_OPTION              = 'tva_paypal_refresh_token';
	/** @deprecated Unused in new Product API bearer-token flow. */
	public const REFRESH_TOKEN_OPTION_LIVE         = 'tva_paypal_refresh_token_live';
	/** @deprecated Unused in new Product API bearer-token flow. */
	public const EXPIRES_AT_OPTION                 = 'tva_paypal_expires_at';
	/** @deprecated Unused in new Product API bearer-token flow. */
	public const EXPIRES_AT_OPTION_LIVE            = 'tva_paypal_expires_at_live';
	public const MERCHANT_ID_OPTION                = 'tva_paypal_merchant_id';
	public const MERCHANT_ID_OPTION_LIVE           = 'tva_paypal_merchant_id_live';
	public const COUNTRY_OPTION                    = 'tva_paypal_merchant_country';
	public const COUNTRY_OPTION_LIVE               = 'tva_paypal_merchant_country_live';
	public const EMAIL_CONFIRMED_OPTION            = 'tva_paypal_primary_email_confirmed';
	public const EMAIL_OPTION                      = 'tva_paypal_primary_email';       // test mode
	public const EMAIL_OPTION_LIVE                 = 'tva_paypal_primary_email_live';   // live mode
	public const PAYMENTS_RECEIVABLE_OPTION        = 'tva_paypal_payments_receivable';
	public const LIVE_COUNT_OPTION                 = 'tva_paypal_live_count';
	public const TEST_COUNT_OPTION                 = 'tva_paypal_test_count';
	public const SITE_SECRET_OPTION                = 'tva_paypal_site_secret';
	public const SITE_SECRET_OPTION_LIVE           = 'tva_paypal_site_secret_live';
	public const WEBHOOK_SECRET_OPTION             = 'tva_paypal_webhook_secret';
	public const WEBHOOK_SECRET_OPTION_LIVE        = 'tva_paypal_webhook_secret_live';
	public const REFERRAL_TOKEN_OPTION             = 'tva_paypal_referral_token';
	public const REFERRAL_TOKEN_OPTION_LIVE        = 'tva_paypal_referral_token_live';
	public const PENDING_OPTION                    = 'tva_paypal_onboarding_pending';
	public const PENDING_OPTION_LIVE               = 'tva_paypal_onboarding_pending_live';
	public const CLIENT_ID_OPTION                  = 'tva_paypal_client_id';
	public const CLIENT_ID_OPTION_LIVE             = 'tva_paypal_client_id_live';
	public const SDK_TOKEN_OPTION                  = 'tva_paypal_sdk_token';
	public const SDK_TOKEN_OPTION_LIVE             = 'tva_paypal_sdk_token_live';
	// Raw per-mode capability cache from GET /merchant (webhook-maintained; for later phases).
	public const CAPABILITIES_OPTION               = 'tva_paypal_merchant_capabilities_test';
	public const CAPABILITIES_OPTION_LIVE          = 'tva_paypal_merchant_capabilities_live';
	// Sanitized capabilities_summary from GET /merchant (schema_version 1), per mode.
	public const CAPABILITIES_SUMMARY_OPTION       = 'tva_paypal_capabilities_summary';
	public const CAPABILITIES_SUMMARY_OPTION_LIVE  = 'tva_paypal_capabilities_summary_live';
	public const VETTING_STATUS_OPTION             = 'tva_paypal_vetting_status';       // test mode
	public const VETTING_STATUS_OPTION_LIVE        = 'tva_paypal_vetting_status_live';  // live mode

	/**
	 * Required length of the site secret (hex chars). Generated by the plugin via bin2hex( random_bytes( 16 ) ).
	 */
	public const SITE_SECRET_LENGTH = 32;

	/**
	 * Get the TEST access token.
	 *
	 * @return string
	 */
	public static function get_token() {
		return (string) get_option( static::ACCESS_TOKEN_OPTION, '' );
	}

	/**
	 * Get the LIVE access token.
	 *
	 * @return string
	 */
	public static function get_token_live() {
		return (string) get_option( static::ACCESS_TOKEN_OPTION_LIVE, '' );
	}

	/**
	 * Get the TEST refresh token.
	 *
	 * @return string
	 */
	public static function get_refresh_token() {
		return (string) get_option( static::REFRESH_TOKEN_OPTION, '' );
	}

	/**
	 * Get the LIVE refresh token.
	 *
	 * @return string
	 */
	public static function get_refresh_token_live() {
		return (string) get_option( static::REFRESH_TOKEN_OPTION_LIVE, '' );
	}

	/**
	 * Get the TEST merchant (account) ID.
	 *
	 * @return string
	 */
	public static function get_account_id() {
		return (string) get_option( static::MERCHANT_ID_OPTION, '' );
	}

	/**
	 * Get the LIVE merchant (account) ID.
	 *
	 * @return string
	 */
	public static function get_account_id_live() {
		return (string) get_option( static::MERCHANT_ID_OPTION_LIVE, '' );
	}

	/**
	 * Save the TEST merchant ID.
	 *
	 * @param string $id
	 */
	public static function save_account_id( $id ) {
		update_option( static::MERCHANT_ID_OPTION, $id, false );
	}

	/**
	 * Save the LIVE merchant ID.
	 *
	 * @param string $id
	 */
	public static function save_account_id_live( $id ) {
		update_option( static::MERCHANT_ID_OPTION_LIVE, $id, false );
	}

	/**
	 * Get the PayPal account email for the given mode.
	 *
	 * @param string $mode 'live' or 'test'
	 * @return string
	 */
	public static function get_merchant_email( $mode = 'live' ) {
		$key = 'live' === $mode ? static::EMAIL_OPTION_LIVE : static::EMAIL_OPTION;
		return (string) get_option( $key, '' );
	}

	/**
	 * Save the PayPal account email for the given mode.
	 *
	 * @param string $email
	 * @param string $mode 'live' or 'test'
	 */
	public static function save_merchant_email( $email, $mode = 'live' ) {
		$key = 'live' === $mode ? static::EMAIL_OPTION_LIVE : static::EMAIL_OPTION;
		update_option( $key, sanitize_email( (string) $email ), false );
	}

	/**
	 * Get (or lazily create) the credentials endpoint slug.
	 *
	 * Stored in wp_options with autoload = false. The slug becomes part of the
	 * REST URL PayPal redirects back to after OAuth — kept stable across requests.
	 *
	 * @param string $mode 'live' or 'test'
	 *
	 * @return string
	 */
	public static function get_credentials_endpoint( $mode = 'live' ) {
		$option_name = $mode === 'live'
			? static::CREDENTIALS_ENDPOINT_OPTION_LIVE
			: static::CREDENTIALS_ENDPOINT_OPTION;

		$endpoint = get_option( $option_name, false );

		if ( ! $endpoint ) {
			$endpoint = static::generate_endpoint_slug();
			update_option( $option_name, $endpoint, false );
			static::clear_object_cache( $option_name );
		}

		return $endpoint;
	}

	/**
	 * Generate a 16-char endpoint slug, preferring the CSPRNG.
	 *
	 * random_bytes() can throw on entropy/OS failure. This slug is generated lazily during
	 * REST route registration (TVA_PayPal_Controller::register_routes()), where an uncaught
	 * throw would fatal route setup and leave the PayPal gateway with no endpoints at all —
	 * including the webhook listener. Fall back to wp_generate_password() (backed by wp_rand)
	 * so slug generation can never fatal a request.
	 *
	 * @return string 16-character slug.
	 */
	protected static function generate_endpoint_slug() {
		try {
			return bin2hex( random_bytes( 8 ) ); // 16-char hex, CSPRNG
		} catch ( \Throwable $e ) {
			return strtolower( wp_generate_password( 16, false, false ) );
		}
	}

	/**
	 * Generate a cryptographically random state token for OAuth CSRF protection.
	 *
	 * @return string 80-character padded hex string
	 * @throws RandomException
	 */
	public static function generate_state() {
		$pad = substr( uniqid( 'paypal-', true ), 0, 20 );

		return str_pad( bin2hex( random_bytes( 16 ) ), 80, $pad, STR_PAD_BOTH );
	}

	/**
	 * Get (or lazily create) the TEST OAuth state token.
	 *
	 * @return string
	 * @throws RandomException
	 */
	public static function get_state() {
		static::clear_object_cache( static::STATE_OPTION );
		$state = get_option( static::STATE_OPTION );

		if ( ! $state ) {
			$state = static::generate_state();
			update_option( static::STATE_OPTION, $state, false );
		}

		return $state;
	}

	/**
	 * Get (or lazily create) the LIVE OAuth state token.
	 *
	 * @return string
	 * @throws RandomException
	 */
	public static function get_state_live() {
		static::clear_object_cache( static::STATE_OPTION_LIVE );
		$state = get_option( static::STATE_OPTION_LIVE );

		if ( ! $state ) {
			$state = static::generate_state();
			update_option( static::STATE_OPTION_LIVE, $state, false );
		}

		return $state;
	}

	/**
	 * Delete the TEST state token (called after successful OAuth exchange).
	 */
	public static function delete_state() {
		delete_option( static::STATE_OPTION );
	}

	/**
	 * Delete the LIVE state token (called after successful OAuth exchange).
	 */
	public static function delete_state_live() {
		delete_option( static::STATE_OPTION_LIVE );
	}

	/**
	 * Normalise an expiry value to an ISO-8601 string.
	 *
	 * PayPal OAuth responses may send expires_at as an ISO string ("2027-01-01T00:00:00Z")
	 * or as a Unix integer. Storing always as ISO-8601 keeps strtotime() reliable.
	 *
	 * @param string|int $expires_at
	 *
	 * @return string
	 */
	public static function normalise_expires_at( $expires_at ) {
		if ( is_numeric( $expires_at ) ) {
			return gmdate( 'Y-m-d\TH:i:s\Z', (int) $expires_at );
		}

		return (string) $expires_at;
	}

	/**
	 * Persist all credential values for one mode at once.
	 *
	 * expires_at is normalised to ISO-8601 before storage.
	 *
	 * @param string     $access_token
	 * @param string     $refresh_token
	 * @param string|int $expires_at    ISO 8601 string or Unix timestamp integer
	 * @param string     $mode          'live' or 'test'
	 * @param string     $merchant_id
	 *
	 * @return bool
	 */
	public static function save_credentials( $access_token, $refresh_token, $expires_at, $mode, $merchant_id ) {
		$normalised_expiry = static::normalise_expires_at( $expires_at );

		if ( $mode === 'live' ) {
			update_option( static::ACCESS_TOKEN_OPTION_LIVE, $access_token, false );
			update_option( static::REFRESH_TOKEN_OPTION_LIVE, $refresh_token, false );
			update_option( static::EXPIRES_AT_OPTION_LIVE, $normalised_expiry, false );
			static::save_account_id_live( $merchant_id );
			static::delete_state_live();
		} else {
			update_option( static::ACCESS_TOKEN_OPTION, $access_token, false );
			update_option( static::REFRESH_TOKEN_OPTION, $refresh_token, false );
			update_option( static::EXPIRES_AT_OPTION, $normalised_expiry, false );
			static::save_account_id( $merchant_id );
			static::delete_state();
		}

		return true;
	}

	/**
	 * Return whether a given mode has valid credentials (merchant ID + site secret).
	 *
	 * @param string $mode 'live' or 'test'
	 *
	 * @return bool
	 */
	public static function is_mode_enabled( $mode ) {
		return ! empty( static::get_merchant_id( $mode ) )
			&& strlen( static::get_site_secret( $mode ) ) === static::SITE_SECRET_LENGTH;
	}

	/**
	 * Persist the Product API's capabilities_summary block for a mode.
	 * Rejects unknown schema versions so a contract change can't poison the UI;
	 * whitelists the fields the admin grid consumes.
	 *
	 * Note: `extra` values are sanitized recursively — nested structure and
	 * scalar types (bool/int/float) are preserved; string leaves are sanitized.
	 *
	 * @param array  $summary Decoded capabilities_summary from GET /merchant.
	 * @param string $mode    'live' or 'test' (required; no default).
	 *
	 * @return bool Whether the summary was accepted and stored.
	 */
	public static function save_capabilities_summary( array $summary, string $mode ) {
		if ( (int) ( $summary['schema_version'] ?? 0 ) !== 1 ) {
			if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
				error_log( sprintf(
					'TVA PayPal: rejected capabilities_summary with schema_version %s (only 1 is supported) — keeping the previously stored summary.',
					wp_json_encode( $summary['schema_version'] ?? null )
				) );
			}

			return false;
		}

		$clean = [ 'groups' => [], 'rollup' => [] ];

		foreach ( (array) ( $summary['groups'] ?? [] ) as $group ) {
			if ( empty( $group['key'] ) ) {
				continue;
			}
			$clean_group = [
				'key'   => sanitize_key( $group['key'] ),
				'label' => sanitize_text_field( $group['label'] ?? '' ),
				'items' => [],
			];
			foreach ( (array) ( $group['items'] ?? [] ) as $item ) {
				if ( empty( $item['key'] ) ) {
					continue;
				}
				$clean_item = [
					'key'        => sanitize_key( $item['key'] ),
					'label'      => sanitize_text_field( $item['label'] ?? '' ),
					'status'     => strtoupper( sanitize_text_field( $item['status'] ?? '' ) ),
					'renderable' => ! empty( $item['renderable'] ),
				];
				if ( ! empty( $item['extra'] ) && is_array( $item['extra'] ) ) {
					$clean_item['extra'] = static::sanitize_extra( $item['extra'] );
				}
				if ( ! empty( $item['vetting'] ) && is_array( $item['vetting'] ) ) {
					$clean_item['vetting'] = [
						'vetting_status'    => strtoupper( sanitize_text_field( $item['vetting']['vetting_status'] ?? '' ) ),
						'capability_status' => strtoupper( sanitize_text_field( $item['vetting']['capability_status'] ?? '' ) ),
						'limits'            => static::sanitize_extra( (array) ( $item['vetting']['limits'] ?? [] ) ),
					];
				}
				$clean_group['items'][] = $clean_item;
			}
			$clean['groups'][] = $clean_group;
		}

		$rollup          = (array) ( $summary['rollup'] ?? [] );
		$clean['rollup'] = [
			'all_ready'        => ! empty( $rollup['all_ready'] ),
			'any_pending'      => ! empty( $rollup['any_pending'] ),
			'renderable_count' => (int) ( $rollup['renderable_count'] ?? 0 ),
			'pending'          => array_map( 'sanitize_key', (array) ( $rollup['pending'] ?? [] ) ),
			'missing'          => array_map( 'sanitize_key', (array) ( $rollup['missing'] ?? [] ) ),
		];

		$option = $mode === 'live' ? static::CAPABILITIES_SUMMARY_OPTION_LIVE : static::CAPABILITIES_SUMMARY_OPTION;
		update_option( $option, $clean, false );

		return true;
	}

	/**
	 * Recursively sanitize a summary item's `extra` metadata, preserving the
	 * nested structure and scalar types: bool/int/float pass through unchanged
	 * (so the localized JS payload keeps real booleans), strings are sanitized.
	 *
	 * @param array $extra
	 *
	 * @return array
	 */
	private static function sanitize_extra( array $extra ) {
		$clean = [];
		foreach ( $extra as $key => $value ) {
			$key = sanitize_key( $key );
			if ( is_array( $value ) ) {
				$clean[ $key ] = static::sanitize_extra( $value );
			} elseif ( is_bool( $value ) || is_int( $value ) || is_float( $value ) ) {
				$clean[ $key ] = $value;
			} else {
				$clean[ $key ] = sanitize_text_field( (string) $value );
			}
		}

		return $clean;
	}

	/**
	 * Stored capabilities_summary for a mode. Defaults to the live summary when
	 * live is connected, the test one otherwise (mirrors which connection the
	 * settings page treats as primary).
	 *
	 * @param string|null $mode 'live', 'test' or null for auto.
	 *
	 * @return array{groups:array,rollup:array}
	 */
	public static function get_capabilities_summary( $mode = null ) {
		if ( $mode === null ) {
			$mode = static::is_mode_enabled( 'live' ) ? 'live' : 'test';
		}

		$option = $mode === 'live' ? static::CAPABILITIES_SUMMARY_OPTION_LIVE : static::CAPABILITIES_SUMMARY_OPTION;
		$stored = get_option( $option, [] );

		if ( ! is_array( $stored ) || empty( $stored['groups'] ) ) {
			return [ 'groups' => [], 'rollup' => [] ];
		}

		return [
			'groups' => (array) $stored['groups'],
			'rollup' => (array) ( $stored['rollup'] ?? [] ),
		];
	}

	/**
	 * Keys of the buyer-facing (renderable) items across all summary groups —
	 * the only keys the checkout-method display toggles accept. The contract
	 * guarantees renderable implies ACTIVE; the status check makes a contract
	 * violation fail closed for every consumer (toggles, REST, JS payload).
	 *
	 * @param string|null $mode 'live', 'test' or null for auto.
	 *
	 * @return string[]
	 */
	public static function get_renderable_keys( $mode = null ) {
		$keys = [];
		foreach ( static::get_capabilities_summary( $mode )['groups'] as $group ) {
			foreach ( (array) ( $group['items'] ?? [] ) as $item ) {
				if ( ! empty( $item['renderable'] ) && ! empty( $item['key'] ) && ( $item['status'] ?? '' ) === 'ACTIVE' ) {
					$keys[] = $item['key'];
				}
			}
		}

		return array_values( array_unique( $keys ) );
	}

	/**
	 * Whether the merchant's primary PayPal email is confirmed.
	 *
	 * @return bool
	 */
	public static function is_email_confirmed() {
		return (bool) get_option( static::EMAIL_CONFIRMED_OPTION, false );
	}

	/**
	 * Whether the merchant can currently receive funds.
	 *
	 * @return bool
	 */
	public static function is_payments_receivable() {
		return (bool) get_option( static::PAYMENTS_RECEIVABLE_OPTION, false );
	}

	/**
	 * Number of Thrive Apprentice products that have a PayPal price configured.
	 *
	 * Computed dynamically by scanning products for a PayPal pricing rule (same
	 * approach as Square's get_protected_products_count) rather than reading a
	 * stored counter, which was never maintained. PayPal pricing rules are not
	 * mode-specific, so the count is attributed to the currently-connected mode;
	 * the other mode reports 0.
	 *
	 * @param bool $live
	 *
	 * @return int
	 */
	public static function get_protected_products_count( $live = true ) {
		$mode = $live ? 'live' : 'test';

		if ( ! static::is_mode_enabled( $mode ) ) {
			return 0;
		}

		$products = \TVA\Product::get_items();
		$products = ( is_array( $products ) || is_object( $products ) ) ? $products : [];

		$count = 0;
		foreach ( $products as $product ) {
			// TVA\Product defines __get() but not __isset(), so isset( $product->ID )
			// is always false; read the id via the canonical accessor instead.
			$product_id = (int) $product->get_id();
			if ( $product_id <= 0 ) {
				continue;
			}

			$rule = Settings::get_product_rule( $product_id );
			if ( ! empty( $rule['amount'] ) && ! empty( $rule['currency'] ) ) {
				$count++;
			}
		}

		return $count;
	}

	/**
	 * Persist merchant readiness flags (email-confirmed, payments-receivable).
	 * Called by the controller's verify_merchant() after a GET /merchant, on
	 * connect and on the settings-page status refresh. Capability data is
	 * persisted separately via save_capabilities_summary().
	 *
	 * @param bool $email_confirmed
	 * @param bool $payments_receivable
	 */
	public static function save_merchant_status( $email_confirmed, $payments_receivable = false ) {
		update_option( static::EMAIL_CONFIRMED_OPTION, (bool) $email_confirmed, false );
		update_option( static::PAYMENTS_RECEIVABLE_OPTION, (bool) $payments_receivable, false );
	}

	public static function save_vetting_status( string $status, string $mode ): void {
		$key = 'live' === $mode ? static::VETTING_STATUS_OPTION_LIVE : static::VETTING_STATUS_OPTION;
		update_option( $key, strtoupper( sanitize_text_field( $status ) ), false );
	}

	public static function get_vetting_status( string $mode ): string {
		$key = 'live' === $mode ? static::VETTING_STATUS_OPTION_LIVE : static::VETTING_STATUS_OPTION;
		return (string) get_option( $key, '' );
	}

	public static function is_vetting_approved( string $mode ): bool {
		return in_array( static::get_vetting_status( $mode ), [ 'SUBSCRIBED', 'APPROVED' ], true );
	}

	public static function is_vetting_blocking( string $mode ): bool {
		$status = static::get_vetting_status( $mode );
		return '' !== $status && ! in_array( $status, [ 'SUBSCRIBED', 'APPROVED' ], true );
	}

	/**
	 * Map a capability item's vetting sub-state to a seller-facing phase.
	 *
	 * Maps PayPal's documented `vetting_status` enum (Partner Referrals v1 Product schema:
	 * APPROVED, PENDING, DECLINED, SUBSCRIBED, IN_REVIEW, NEED_MORE_DATA, DENIED) to a phase,
	 * with `capability_status` as a fallback signal. Unknown values return '' (no notice) so a
	 * benign/unrecognized state never raises a false action-required banner.
	 *
	 * @param array $vetting { vetting_status, capability_status, limits }
	 * @return string '' | 'approved' | 'in_review' | 'needs_info' | 'denied'
	 */
	public static function vetting_phase( array $vetting ): string {
		$vs = strtoupper( (string) ( $vetting['vetting_status'] ?? '' ) );
		$cs = strtoupper( (string) ( $vetting['capability_status'] ?? '' ) );

		if ( $cs === 'DENIED' || in_array( $vs, [ 'DENIED', 'DECLINED' ], true ) ) {
			return 'denied';
		}
		// Conservative: only an explicit NEED_MORE_DATA fires the action banner.
		// `limits` alone does NOT — SUBSCRIBED_WITH_LIMIT-style states are often
		// benign, and a false action-required banner is worse than a missed one.
		if ( $vs === 'NEED_MORE_DATA' ) {
			return 'needs_info';
		}
		if ( in_array( $vs, [ 'SUBSCRIBED', 'APPROVED' ], true ) || $cs === 'ACTIVE' ) {
			return 'approved';
		}
		if ( in_array( $cs, [ 'PENDING', 'IN_REVIEW' ], true ) || in_array( $vs, [ 'IN_REVIEW', 'PENDING' ], true ) ) {
			return 'in_review';
		}
		return '';
	}

	/**
	 * Capability items whose vetting needs seller attention (needs_info/denied),
	 * for the admin action banner. In-review is intentionally excluded (shown as a pill).
	 *
	 * @param string|null $mode 'live', 'test' or null for auto.
	 * @return array<int,array{key:string,label:string,phase:string}>
	 */
	public static function get_vetting_alerts( $mode = null ): array {
		$alerts = [];
		foreach ( static::get_capabilities_summary( $mode )['groups'] as $group ) {
			foreach ( (array) ( $group['items'] ?? [] ) as $item ) {
				if ( empty( $item['vetting'] ) || ! is_array( $item['vetting'] ) ) {
					continue;
				}
				$phase = static::vetting_phase( $item['vetting'] );
				if ( in_array( $phase, [ 'needs_info', 'denied' ], true ) ) {
					$alerts[] = [
						'key'   => $item['key'] ?? '',
						'label' => $item['label'] ?: ( $item['key'] ?? '' ),
						'phase' => $phase,
					];
				}
			}
		}
		return $alerts;
	}

	/**
	 * Remove all PayPal credential options from wp_options.
	 *
	 * IMPORTANT — this method only clears credentials; it does NOT cancel subscriptions.
	 * The D17 subscription wind-down (cancel each active vault subscription at period end)
	 * is performed by Subscription_Winddown::run(), which MUST be called BEFORE this method
	 * while the bearer token is still live. Once credentials are
	 * gone the cancel calls would fail and any renewal webhooks would be silently dropped
	 * (the webhook secret is cleared below), leaving subscribers billed with no order or
	 * access update recorded.
	 *
	 * The admin-initiated disconnect endpoint runs the wind-down first; the admin UI warns
	 * the merchant beforehand, showing the count of active/grace-period subscriptions.
	 */
	public static function disconnect() {
		// New flow options
		static::delete_state();
		static::delete_state_live();
		delete_option( static::SITE_SECRET_OPTION );
		delete_option( static::SITE_SECRET_OPTION_LIVE );
		delete_option( static::REFERRAL_TOKEN_OPTION );
		delete_option( static::REFERRAL_TOKEN_OPTION_LIVE );
		delete_option( static::CLIENT_ID_OPTION );
		delete_option( static::CLIENT_ID_OPTION_LIVE );
		delete_option( static::SDK_TOKEN_OPTION );
		delete_option( static::SDK_TOKEN_OPTION_LIVE );
		delete_option( static::WEBHOOK_SECRET_OPTION );
		delete_option( static::WEBHOOK_SECRET_OPTION_LIVE );
		delete_option( static::MERCHANT_ID_OPTION );
		delete_option( static::MERCHANT_ID_OPTION_LIVE );
		delete_option( static::COUNTRY_OPTION );
		delete_option( static::COUNTRY_OPTION_LIVE );
		delete_option( static::CREDENTIALS_ENDPOINT_OPTION );
		delete_option( static::CREDENTIALS_ENDPOINT_OPTION_LIVE );
		// Bearer token transients
		foreach ( [ 'onboarding', 'order', 'vault' ] as $client ) {
			foreach ( [ 'live', 'test' ] as $mode ) {
				delete_transient( \TVA\PayPal\Http\Base_Client::make_transient_key( $client, $mode ) );
			}
		}
		// Legacy OAuth options (migration safety for existing installs)
		delete_option( static::ACCESS_TOKEN_OPTION );
		delete_option( static::ACCESS_TOKEN_OPTION_LIVE );
		delete_option( static::REFRESH_TOKEN_OPTION );
		delete_option( static::REFRESH_TOKEN_OPTION_LIVE );
		delete_option( static::EXPIRES_AT_OPTION );
		delete_option( static::EXPIRES_AT_OPTION_LIVE );
		delete_option( static::CAPABILITIES_OPTION );      // raw per-mode cache (test)
		delete_option( static::CAPABILITIES_OPTION_LIVE ); // raw per-mode cache (live)
		delete_option( static::CAPABILITIES_SUMMARY_OPTION );
		delete_option( static::CAPABILITIES_SUMMARY_OPTION_LIVE );
		delete_option( static::VETTING_STATUS_OPTION );
		delete_option( static::VETTING_STATUS_OPTION_LIVE );
		delete_option( static::EMAIL_CONFIRMED_OPTION );
		delete_option( static::EMAIL_OPTION );
		delete_option( static::EMAIL_OPTION_LIVE );
		delete_option( static::PAYMENTS_RECEIVABLE_OPTION );
		delete_option( static::LIVE_COUNT_OPTION );
		delete_option( static::TEST_COUNT_OPTION );
		Settings::reset();
		// Invalidate any per-request caches held by Connection (no-op after #3769,
		// kept so future additions to Connection::reset() take effect automatically).
		Connection::reset();
		// Drop Apple Pay domain state (static file + records) so a reconnecting
		// merchant doesn't inherit the previous account's registration/file.
		\TVA\PayPal\Apple_Pay::uninstall();
	}

	/**
	 * Clear the WP Object Cache for a given option key.
	 *
	 * @param string $key
	 */
	public static function clear_object_cache( $key ) {
		wp_cache_delete( $key, 'options' );
	}

	/**
	 * Return the PayPal BN partner code for the given mode.
	 *
	 * @param string $mode 'live' or 'test'
	 * @return string
	 */
	public static function get_bn_code( $mode = 'live' ) {
		return $mode === 'live' ? 'ThriveThemesPPCP_SP' : 'ThriveThemesPPCP_SP_TEST';
	}

	/**
	 * Return the stored merchant ID for the given mode.
	 *
	 * Delegates to get_account_id / get_account_id_live to avoid duplicate storage.
	 *
	 * @param string $mode 'live' or 'test'
	 * @return string
	 */
	public static function get_merchant_id( $mode = 'live' ) {
		return $mode === 'live' ? static::get_account_id_live() : static::get_account_id();
	}

	/**
	 * Save the merchant ID for the given mode.
	 *
	 * @param string $id
	 * @param string $mode 'live' or 'test'
	 */
	public static function save_merchant_id( $id, $mode = 'live' ) {
		if ( $mode === 'live' ) {
			static::save_account_id_live( $id );
		} else {
			static::save_account_id( $id );
		}
	}

	/**
	 * Return the buyer's stored PayPal customer id for the given mode.
	 *
	 * PayPal mints a customer.id the first time a buyer vaults a method; we store it
	 * per WP user so subsequent vaults attach to the same PayPal customer.
	 *
	 * @param int    $user_id WP user id.
	 * @param string $mode    'live' or 'test'.
	 * @return string Stored customer id, or '' when none / no user.
	 */
	public static function get_customer_id( $user_id, $mode = 'live' ) {
		$user_id = (int) $user_id;
		if ( $user_id <= 0 ) {
			return '';
		}
		return (string) get_user_meta( $user_id, 'tva_paypal_customer_id_' . $mode, true );
	}

	/**
	 * Store the buyer's PayPal customer id for the given mode. Write-once: an existing
	 * non-empty value is never overwritten (PayPal keeps the same customer for a buyer).
	 *
	 * @param int    $user_id WP user id.
	 * @param string $id      PayPal customer id.
	 * @param string $mode    'live' or 'test'.
	 */
	public static function save_customer_id( $user_id, $id, $mode = 'live' ) {
		$user_id = (int) $user_id;
		$id      = sanitize_text_field( (string) $id );
		if ( $user_id <= 0 || $id === '' ) {
			return;
		}
		if ( static::get_customer_id( $user_id, $mode ) !== '' ) {
			return;
		}
		// Write-once, so a false return here is a real failure (not an unchanged value): this is
		// the buyer's vault-customer anchor, so surface it in the log rather than failing silently.
		if ( false === update_user_meta( $user_id, 'tva_paypal_customer_id_' . $mode, $id ) ) {
			\TVA_Logger::set_type( 'PayPal' );
			\TVA_Logger::log( 'customer_id_store_failed', [ 'user_id' => $user_id, 'mode' => $mode ], true );
		}
	}

	/**
	 * Return the stored site secret for the given mode.
	 *
	 * @param string $mode 'live' or 'test'
	 * @return string
	 */
	public static function get_site_secret( $mode = 'live' ) {
		$key = $mode === 'live' ? static::SITE_SECRET_OPTION_LIVE : static::SITE_SECRET_OPTION;
		return (string) get_option( $key, '' );
	}

	/**
	 * Save the site secret for the given mode.
	 *
	 * @param string $secret
	 * @param string $mode 'live' or 'test'
	 */
	public static function save_site_secret( $secret, $mode = 'live' ) {
		$key = $mode === 'live' ? static::SITE_SECRET_OPTION_LIVE : static::SITE_SECRET_OPTION;
		update_option( $key, $secret, false );
	}

	/**
	 * Merchant country (ISO 3166-1 alpha-2, uppercased) for the given mode.
	 *
	 * Returned by the Product API on /onboarding/complete and GET /merchant;
	 * persisted at connect and refreshed on status checks. Used to gate the
	 * subscription RBM `usage_pattern=SUBSCRIPTION_PREPAID` SDK param to US
	 * merchants. Empty when PayPal omits it — callers must treat empty as
	 * "not US" (fail-safe), never assume a country.
	 *
	 * @param string $mode 'live' or 'test'
	 * @return string Two-letter code, or '' when unknown.
	 */
	public static function get_merchant_country( $mode = 'live' ) {
		$key = $mode === 'live' ? static::COUNTRY_OPTION_LIVE : static::COUNTRY_OPTION;
		return strtoupper( (string) get_option( $key, '' ) );
	}

	/**
	 * Persist the merchant country for the given mode.
	 *
	 * @param string $country ISO 3166-1 alpha-2 (e.g. "US"); empty clears it.
	 * @param string $mode    'live' or 'test'
	 */
	public static function save_merchant_country( $country, $mode = 'live' ) {
		$key   = $mode === 'live' ? static::COUNTRY_OPTION_LIVE : static::COUNTRY_OPTION;
		$value = strtoupper( substr( preg_replace( '/[^A-Za-z]/', '', (string) $country ), 0, 2 ) );
		update_option( $key, $value, false );
	}

	/**
	 * Return the stored referral token for the given mode.
	 *
	 * @param string $mode 'live' or 'test'
	 * @return string
	 */
	public static function get_referral_token( $mode = 'live' ) {
		$key = $mode === 'live' ? static::REFERRAL_TOKEN_OPTION_LIVE : static::REFERRAL_TOKEN_OPTION;
		return (string) get_option( $key, '' );
	}

	/**
	 * Save the referral token for the given mode.
	 *
	 * @param string $token Referral token returned by /onboarding/start.
	 * @param string $mode  'live' or 'test'.
	 *
	 * @return void
	 */
	public static function save_referral_token( $token, $mode = 'live' ) {
		$key = $mode === 'live' ? static::REFERRAL_TOKEN_OPTION_LIVE : static::REFERRAL_TOKEN_OPTION;
		update_option( $key, $token, false );
	}

	/**
	 * Return the stored client ID for the given mode.
	 *
	 * @param string $mode 'live' or 'test'
	 * @return string
	 */
	public static function get_client_id( $mode = 'live' ) {
		$key = $mode === 'live' ? static::CLIENT_ID_OPTION_LIVE : static::CLIENT_ID_OPTION;
		return (string) get_option( $key, '' );
	}

	/**
	 * Save the client ID for the given mode.
	 *
	 * @param string $id   PayPal client ID from /onboarding/complete.
	 * @param string $mode 'live' or 'test'.
	 *
	 * @return void
	 */
	public static function save_client_id( $id, $mode = 'live' ) {
		$key = $mode === 'live' ? static::CLIENT_ID_OPTION_LIVE : static::CLIENT_ID_OPTION;
		update_option( $key, $id, false );
	}

	/**
	 * Return the stored SDK token for the given mode.
	 *
	 * @param string $mode 'live' or 'test'
	 * @return string
	 */
	public static function get_sdk_token( $mode = 'live' ) {
		$key = $mode === 'live' ? static::SDK_TOKEN_OPTION_LIVE : static::SDK_TOKEN_OPTION;
		return (string) get_option( $key, '' );
	}

	/**
	 * Save the SDK token for the given mode.
	 *
	 * @param string $token SDK client token from /onboarding/complete, used to initialise the JS SDK.
	 * @param string $mode  'live' or 'test'.
	 *
	 * @return void
	 */
	public static function save_sdk_token( $token, $mode = 'live' ) {
		$key = $mode === 'live' ? static::SDK_TOKEN_OPTION_LIVE : static::SDK_TOKEN_OPTION;
		update_option( $key, $token, false );
	}

	/**
	 * Return the stored webhook secret for the given mode.
	 *
	 * @param string $mode 'live' or 'test'
	 * @return string
	 */
	public static function get_webhook_secret( $mode = 'live' ) {
		$key = $mode === 'live' ? static::WEBHOOK_SECRET_OPTION_LIVE : static::WEBHOOK_SECRET_OPTION;
		return (string) get_option( $key, '' );
	}

	/**
	 * Save the webhook secret for the given mode.
	 *
	 * Called after /onboarding/complete (or equivalent) returns the secret.
	 *
	 * @param string $secret
	 * @param string $mode 'live' or 'test'
	 */
	public static function save_webhook_secret( $secret, $mode = 'live' ) {
		$key = $mode === 'live' ? static::WEBHOOK_SECRET_OPTION_LIVE : static::WEBHOOK_SECRET_OPTION;
		update_option( $key, $secret, false );
	}

	/**
	 * Return whether a webhook secret is stored for the given mode.
	 *
	 * @param string $mode 'live' or 'test'
	 * @return bool
	 */
	public static function has_webhook_secret( $mode = 'live' ) {
		return ! empty( static::get_webhook_secret( $mode ) );
	}

	/**
	 * Option name for the pending-onboarding record in the given mode.
	 *
	 * @param string $mode 'live' | 'test'
	 * @return string
	 */
	protected static function pending_option( string $mode ): string {
		return 'live' === $mode ? static::PENDING_OPTION_LIVE : static::PENDING_OPTION;
	}

	/**
	 * Persist the pending-onboarding record written when /onboarding/complete
	 * returns 202. Read by the webhook nudge, the JS poll, and the page-load retry
	 * to know which merchant is mid-finalize and with what params.
	 *
	 * @param string $mode 'live' | 'test'
	 * @param array  $data merchant_id, referral_token, webhooks_url, site_url, created_at, attempts
	 * @return void
	 */
	public static function save_onboarding_pending( string $mode, array $data ): void {
		update_option( static::pending_option( $mode ), $data, false );
	}

	/**
	 * Read the pending-onboarding record for the given mode (written by
	 * save_onboarding_pending() when /onboarding/complete returns 202).
	 *
	 * @param string $mode 'live' | 'test'
	 * @return array Empty array when no pending onboarding is recorded.
	 */
	public static function get_onboarding_pending( string $mode ): array {
		$data = get_option( static::pending_option( $mode ), [] );
		return is_array( $data ) ? $data : [];
	}

	/**
	 * @param string $mode 'live' | 'test'
	 * @return void
	 */
	public static function clear_onboarding_pending( string $mode ): void {
		delete_option( static::pending_option( $mode ) );
	}

	/**
	 * Save merchant capabilities for the given mode.
	 *
	 * @param array  $capabilities
	 * @param string $mode 'live' or 'test'
	 */
	public static function save_capabilities( array $capabilities, string $mode ): void {
		$key = $mode === 'live' ? static::CAPABILITIES_OPTION_LIVE : static::CAPABILITIES_OPTION;
		update_option( $key, $capabilities, false );
	}

	/**
	 * Return stored merchant capabilities for the given mode.
	 *
	 * @param string $mode 'live' or 'test'
	 * @return array
	 */
	public static function get_capabilities( string $mode ): array {
		$key = $mode === 'live' ? static::CAPABILITIES_OPTION_LIVE : static::CAPABILITIES_OPTION;
		$val = get_option( $key, [] );
		return is_array( $val ) ? $val : [];
	}

	/**
	 * Delete stored merchant capabilities for the given mode.
	 *
	 * @param string $mode 'live' or 'test'
	 */
	public static function delete_capabilities( string $mode ): void {
		$key = $mode === 'live' ? static::CAPABILITIES_OPTION_LIVE : static::CAPABILITIES_OPTION;
		delete_option( $key );
	}

	/**
	 * Delete the stored capabilities_summary for a mode.
	 *
	 * @param string $mode 'live' or 'test'
	 */
	public static function delete_capabilities_summary( string $mode ): void {
		$key = $mode === 'live' ? static::CAPABILITIES_SUMMARY_OPTION_LIVE : static::CAPABILITIES_SUMMARY_OPTION;
		delete_option( $key );
	}

	/**
	 * Remove all stored credentials for a single mode only.
	 *
	 * Use instead of disconnect() when only one mode should be torn down —
	 * e.g. on MERCHANT.PARTNER.CONSENT.REVOKED, where the event is mode-specific
	 * and the other mode should remain connected.
	 *
	 * @param string $mode 'live' or 'test'
	 */
	public static function disconnect_mode( string $mode ): void {
		if ( $mode === 'live' ) {
			static::delete_state_live();
			delete_option( static::SITE_SECRET_OPTION_LIVE );
			delete_option( static::REFERRAL_TOKEN_OPTION_LIVE );
			delete_option( static::CLIENT_ID_OPTION_LIVE );
			delete_option( static::SDK_TOKEN_OPTION_LIVE );
			delete_option( static::WEBHOOK_SECRET_OPTION_LIVE );
			delete_option( static::MERCHANT_ID_OPTION_LIVE );
			delete_option( static::EMAIL_OPTION_LIVE );
			delete_option( static::CREDENTIALS_ENDPOINT_OPTION_LIVE );
			foreach ( [ 'onboarding', 'order', 'vault' ] as $client ) {
				delete_transient( \TVA\PayPal\Http\Base_Client::make_transient_key( $client, 'live' ) );
			}
			delete_option( static::ACCESS_TOKEN_OPTION_LIVE );
			delete_option( static::REFRESH_TOKEN_OPTION_LIVE );
			delete_option( static::EXPIRES_AT_OPTION_LIVE );
			delete_option( static::VETTING_STATUS_OPTION_LIVE );
		} else {
			static::delete_state();
			delete_option( static::SITE_SECRET_OPTION );
			delete_option( static::REFERRAL_TOKEN_OPTION );
			delete_option( static::CLIENT_ID_OPTION );
			delete_option( static::SDK_TOKEN_OPTION );
			delete_option( static::WEBHOOK_SECRET_OPTION );
			delete_option( static::MERCHANT_ID_OPTION );
			delete_option( static::EMAIL_OPTION );
			delete_option( static::CREDENTIALS_ENDPOINT_OPTION );
			foreach ( [ 'onboarding', 'order', 'vault' ] as $client ) {
				delete_transient( \TVA\PayPal\Http\Base_Client::make_transient_key( $client, 'test' ) );
			}
			delete_option( static::ACCESS_TOKEN_OPTION );
			delete_option( static::REFRESH_TOKEN_OPTION );
			delete_option( static::EXPIRES_AT_OPTION );
			delete_option( static::VETTING_STATUS_OPTION );
		}
	}
}
