<div class="ttd-icon-menu"></div>

<div class="td-app-notification-overlay overlay <?php echo !isset( $_GET['notify'] ) ? 'close': '' ?> "></div>
<div class="td-app-notification-drawer <?php echo isset( $_GET['notify'] ) ? 'open': '' ?> ">
    <div class="td-app-notification-holder">
        <div class="td-app-notification-header notification-header-notify-ttb"></div>
        <div class="td-app-notification-wrapper notification-wrapper-notify-ttb"></div>
        <div class="notification-footer notification-footer-notify-ttb"></div>
    </div>
</div>

<div class="ttd-sidebar-container"></div>
<div class="ttd-main-container"></div>
<div class="ttd-preview-container"></div>

<div id="ttd-modals"></div>

<div id="ttd-notification-box"></div>

