<div class="control-grid full-width pb-0">
	<span>
		<?php echo esc_html__( 'Lazy loading your videos will ensure that player assets are only loaded when they are needed to improve your CWV scores.', 'thrive-cb' ); ?>
		<a class="blue-text" href="https://thrivethemes.com/docs/enabling-lazy-loading-for-video-element-in-thrive-architect/" target="_blank">
			<?php echo __( 'Read more', 'thrive-cb' ) ?>
		</a>
	</span>
</div>
