<nav id="tvu-nav">
	<div class="nav-wrapper">
		<div class="tvu-logo tvd-left">
			<a href="<?php echo admin_url( 'admin.php?page=tve_ult_dashboard' ) ?>"
			   title="<?php echo __( 'Thrive Ultimatum Home', 'thrive-ult' ) ?>">
				<img src="<?php echo TVE_Ult_Const::plugin_url() . '/admin/img/tvu-logo-white.png'; ?>"/>
			</a>
		</div>
		<ul class="tvd-right">
			<li>
				<a href="javascript:void(0)" class="tvd-dropdown-button" data-activates="tvu-submenu" data-beloworigin="true" data-hover="false" data-constrainwidth="false">
					<i class="tvd-icon-settings" style="font-size: 12px;"></i>
					<?php echo __( 'Settings', 'thrive-ult' ) ?>
					<i class="tvd-icon-expanded tvd-no-margin-right"></i>
				</a>
			</li>
			<?php do_action( 'tvd_notification_inbox' ); ?>
		</ul>
		<ul id="tvu-submenu" class="tvd-dropdown-content">
			<li>
				<a id="date_time_settings" href="#">
					<i class="tvu-icon-datetime" style="font-size: 18px;"></i>
					<?php echo __( 'Date & Time Settings', 'thrive-ult' ) ?>
				</a>
			</li>
			<li>
				<a id="tu-purge-cache" href="#purge-cache" class="tvd-tooltipped"
				   data-tooltip="<?php echo __( 'Clear the cache for impressions and conversions displayed for each campaign in Ultimatum Dashboard', 'thrive-ult' ) ?>">
					<i class="tvd-icon-loop2" style="font-size: 12px;"></i>
					<?php echo __( 'Purge Cache', 'thrive-ult' ) ?>
				</a>
			</li>
		</ul>
	</div>
</nav>

<div class="td-app-notification-overlay overlay close"></div>
<div class="td-app-notification-drawer">
    <div class="td-app-notification-holder">
        <div class="td-app-notification-header notification-header-notify-tve-ult"></div>
        <div class="td-app-notification-wrapper notification-wrapper-notify-tve-ult"></div>
        <div class="notification-footer notification-footer-notify-tve-ult"></div>
    </div>
</div>
<?php include TVE_DASH_PATH . '/templates/share.phtml'; ?>
