<div class="tvd-modal-content">
	<h4 class="tva-square-migation-title"><?php esc_html_e( 'Are you sure you would like Thrive Apprentice to manage Stripe Products?', 'thrive-apprentice' ); ?></h4>
    <p><?php esc_html_e( 'This change CANNOT be undone and the selected product and price will now be managed by Thrive Apprentice.', 'thrive-apprentice' )?></p>
</div>

<div class="tva-square-product-migration-footer tva-flex tva-align-center tva-flex-center">
    <button type="button" class="click tva-modal-btn tva-modal-btn-close" data-fn="close"><?php echo __( 'No', 'thrive-apprentice' ); ?></button>
    <button type="button" class="click tva-modal-btn tva-price-save-btn" data-fn="manageProduct"><?php echo __( 'Yes', 'thrive-apprentice' ) ?></button>
</div>
