<div class="tcb-tooltip tcb-hamburger-edit-mode-tooltip">
	<div class="tcb-tooltip-text center-text">
		<p class="mb-5">
			<?php echo __( 'When Edit Mode is enabled for the Custom Menu element, you will be able to drag & drop elements inside the Menu Box area for each device type.', 'thrive-cb' ); ?>
		</p>
		<a href="https://thrivethemes.com/docs/how-to-create-an-off-canvas-side-menu-in-thrive-architect/" class="blue-text" target="_blank">
			<?php echo __( 'Click here to learn more', 'thrive-cb' ); ?>
		</a>
	</div>

	<div class="tcb-tooltip-buttons">
		<a href="#" class="tcb-button-dismiss click" data-fn="dismiss">
			<?php echo __( 'GOT IT', 'thrive-cb' ); ?>
		</a>
	</div>
</div>
