<div class="control-grid full-width pb-0">
	<span>
		<?php echo esc_html__( 'Copy the Direct Play from your Bunny.net Stream Library', 'thrive-cb' ); ?>
	</span>
	<span>
	<a class="blue-text" href="https://panel.bunny.net/stream" target="_blank">
		<?php echo __( 'Open Library', 'thrive-cb' ) ?>
	</a>
	<a class="blue-text" href="https://thrivethemes.com/docs/how-to-use-the-video-element-in-thrive-architect/" target="_blank">
		<?php echo __( 'Learn more', 'thrive-cb' ) ?>
	</a>
		</span>
</div>
