<div class="tvd-square-no-test tvd-modal-content">
	<h3 class="tvd-modal-title"><?php esc_html_e( 'Sandbox is not connected', 'thrive-apprentice' ); ?></h3>

    <div class="tva-square-price-wrapper">
        <div>
			<p class="mb-5">
                <?php echo __( 'Go on Square Settings and press the', 'thrive-apprentice' ); ?>
                <a href="<?php echo esc_url( admin_url( 'admin.php?page=thrive_apprentice#settings/payments/square' ) ); ?>" target="_blank">"<?php echo __( 'Connect Sandbox', 'thrive-apprentice' ); ?>"</a>
                <?php echo __( 'button.', 'thrive-apprentice' ); ?>
            </p>
        </div>
        <div>
			
        </div>
    </div>
</div>

<div class="tvd-square-no-test tva-content-price-footer tva-flex tva-align-center">
    <button type="button" class="click tva-modal-btn tva-modal-btn-close" data-fn="close"><?php echo __( 'Got it!', 'thrive-apprentice' ); ?></button>
</div>
